// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package rolemock

import (
	"context"

	"github.com/senthalan/thunder/backend/internal/role"
	"github.com/senthalan/thunder/backend/internal/system/error/serviceerror"
	mock "github.com/stretchr/testify/mock"
)

// NewRoleServiceInterfaceMock creates a new instance of RoleServiceInterfaceMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRoleServiceInterfaceMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *RoleServiceInterfaceMock {
	mock := &RoleServiceInterfaceMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// RoleServiceInterfaceMock is an autogenerated mock type for the RoleServiceInterface type
type RoleServiceInterfaceMock struct {
	mock.Mock
}

type RoleServiceInterfaceMock_Expecter struct {
	mock *mock.Mock
}

func (_m *RoleServiceInterfaceMock) EXPECT() *RoleServiceInterfaceMock_Expecter {
	return &RoleServiceInterfaceMock_Expecter{mock: &_m.Mock}
}

// AddAssignments provides a mock function for the type RoleServiceInterfaceMock
func (_mock *RoleServiceInterfaceMock) AddAssignments(ctx context.Context, id string, assignments []role.RoleAssignment) *serviceerror.ServiceError {
	ret := _mock.Called(ctx, id, assignments)

	if len(ret) == 0 {
		panic("no return value specified for AddAssignments")
	}

	var r0 *serviceerror.ServiceError
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, []role.RoleAssignment) *serviceerror.ServiceError); ok {
		r0 = returnFunc(ctx, id, assignments)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*serviceerror.ServiceError)
		}
	}
	return r0
}

// RoleServiceInterfaceMock_AddAssignments_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddAssignments'
type RoleServiceInterfaceMock_AddAssignments_Call struct {
	*mock.Call
}

// AddAssignments is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - assignments []role.RoleAssignment
func (_e *RoleServiceInterfaceMock_Expecter) AddAssignments(ctx interface{}, id interface{}, assignments interface{}) *RoleServiceInterfaceMock_AddAssignments_Call {
	return &RoleServiceInterfaceMock_AddAssignments_Call{Call: _e.mock.On("AddAssignments", ctx, id, assignments)}
}

func (_c *RoleServiceInterfaceMock_AddAssignments_Call) Run(run func(ctx context.Context, id string, assignments []role.RoleAssignment)) *RoleServiceInterfaceMock_AddAssignments_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []role.RoleAssignment
		if args[2] != nil {
			arg2 = args[2].([]role.RoleAssignment)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *RoleServiceInterfaceMock_AddAssignments_Call) Return(serviceError *serviceerror.ServiceError) *RoleServiceInterfaceMock_AddAssignments_Call {
	_c.Call.Return(serviceError)
	return _c
}

func (_c *RoleServiceInterfaceMock_AddAssignments_Call) RunAndReturn(run func(ctx context.Context, id string, assignments []role.RoleAssignment) *serviceerror.ServiceError) *RoleServiceInterfaceMock_AddAssignments_Call {
	_c.Call.Return(run)
	return _c
}

// CreateRole provides a mock function for the type RoleServiceInterfaceMock
func (_mock *RoleServiceInterfaceMock) CreateRole(ctx context.Context, role1 role.RoleCreationDetail) (*role.RoleWithPermissionsAndAssignments, *serviceerror.ServiceError) {
	ret := _mock.Called(ctx, role1)

	if len(ret) == 0 {
		panic("no return value specified for CreateRole")
	}

	var r0 *role.RoleWithPermissionsAndAssignments
	var r1 *serviceerror.ServiceError
	if returnFunc, ok := ret.Get(0).(func(context.Context, role.RoleCreationDetail) (*role.RoleWithPermissionsAndAssignments, *serviceerror.ServiceError)); ok {
		return returnFunc(ctx, role1)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, role.RoleCreationDetail) *role.RoleWithPermissionsAndAssignments); ok {
		r0 = returnFunc(ctx, role1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*role.RoleWithPermissionsAndAssignments)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, role.RoleCreationDetail) *serviceerror.ServiceError); ok {
		r1 = returnFunc(ctx, role1)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*serviceerror.ServiceError)
		}
	}
	return r0, r1
}

// RoleServiceInterfaceMock_CreateRole_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateRole'
type RoleServiceInterfaceMock_CreateRole_Call struct {
	*mock.Call
}

// CreateRole is a helper method to define mock.On call
//   - ctx context.Context
//   - role1 role.RoleCreationDetail
func (_e *RoleServiceInterfaceMock_Expecter) CreateRole(ctx interface{}, role1 interface{}) *RoleServiceInterfaceMock_CreateRole_Call {
	return &RoleServiceInterfaceMock_CreateRole_Call{Call: _e.mock.On("CreateRole", ctx, role1)}
}

func (_c *RoleServiceInterfaceMock_CreateRole_Call) Run(run func(ctx context.Context, role1 role.RoleCreationDetail)) *RoleServiceInterfaceMock_CreateRole_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 role.RoleCreationDetail
		if args[1] != nil {
			arg1 = args[1].(role.RoleCreationDetail)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *RoleServiceInterfaceMock_CreateRole_Call) Return(roleWithPermissionsAndAssignments *role.RoleWithPermissionsAndAssignments, serviceError *serviceerror.ServiceError) *RoleServiceInterfaceMock_CreateRole_Call {
	_c.Call.Return(roleWithPermissionsAndAssignments, serviceError)
	return _c
}

func (_c *RoleServiceInterfaceMock_CreateRole_Call) RunAndReturn(run func(ctx context.Context, role1 role.RoleCreationDetail) (*role.RoleWithPermissionsAndAssignments, *serviceerror.ServiceError)) *RoleServiceInterfaceMock_CreateRole_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteRole provides a mock function for the type RoleServiceInterfaceMock
func (_mock *RoleServiceInterfaceMock) DeleteRole(ctx context.Context, id string) *serviceerror.ServiceError {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteRole")
	}

	var r0 *serviceerror.ServiceError
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *serviceerror.ServiceError); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*serviceerror.ServiceError)
		}
	}
	return r0
}

// RoleServiceInterfaceMock_DeleteRole_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteRole'
type RoleServiceInterfaceMock_DeleteRole_Call struct {
	*mock.Call
}

// DeleteRole is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *RoleServiceInterfaceMock_Expecter) DeleteRole(ctx interface{}, id interface{}) *RoleServiceInterfaceMock_DeleteRole_Call {
	return &RoleServiceInterfaceMock_DeleteRole_Call{Call: _e.mock.On("DeleteRole", ctx, id)}
}

func (_c *RoleServiceInterfaceMock_DeleteRole_Call) Run(run func(ctx context.Context, id string)) *RoleServiceInterfaceMock_DeleteRole_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *RoleServiceInterfaceMock_DeleteRole_Call) Return(serviceError *serviceerror.ServiceError) *RoleServiceInterfaceMock_DeleteRole_Call {
	_c.Call.Return(serviceError)
	return _c
}

func (_c *RoleServiceInterfaceMock_DeleteRole_Call) RunAndReturn(run func(ctx context.Context, id string) *serviceerror.ServiceError) *RoleServiceInterfaceMock_DeleteRole_Call {
	_c.Call.Return(run)
	return _c
}

// GetAuthorizedPermissions provides a mock function for the type RoleServiceInterfaceMock
func (_mock *RoleServiceInterfaceMock) GetAuthorizedPermissions(ctx context.Context, entityID string, groups []string, requestedPermissions []string) ([]string, *serviceerror.ServiceError) {
	ret := _mock.Called(ctx, entityID, groups, requestedPermissions)

	if len(ret) == 0 {
		panic("no return value specified for GetAuthorizedPermissions")
	}

	var r0 []string
	var r1 *serviceerror.ServiceError
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, []string, []string) ([]string, *serviceerror.ServiceError)); ok {
		return returnFunc(ctx, entityID, groups, requestedPermissions)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, []string, []string) []string); ok {
		r0 = returnFunc(ctx, entityID, groups, requestedPermissions)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, []string, []string) *serviceerror.ServiceError); ok {
		r1 = returnFunc(ctx, entityID, groups, requestedPermissions)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*serviceerror.ServiceError)
		}
	}
	return r0, r1
}

// RoleServiceInterfaceMock_GetAuthorizedPermissions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAuthorizedPermissions'
type RoleServiceInterfaceMock_GetAuthorizedPermissions_Call struct {
	*mock.Call
}

// GetAuthorizedPermissions is a helper method to define mock.On call
//   - ctx context.Context
//   - entityID string
//   - groups []string
//   - requestedPermissions []string
func (_e *RoleServiceInterfaceMock_Expecter) GetAuthorizedPermissions(ctx interface{}, entityID interface{}, groups interface{}, requestedPermissions interface{}) *RoleServiceInterfaceMock_GetAuthorizedPermissions_Call {
	return &RoleServiceInterfaceMock_GetAuthorizedPermissions_Call{Call: _e.mock.On("GetAuthorizedPermissions", ctx, entityID, groups, requestedPermissions)}
}

func (_c *RoleServiceInterfaceMock_GetAuthorizedPermissions_Call) Run(run func(ctx context.Context, entityID string, groups []string, requestedPermissions []string)) *RoleServiceInterfaceMock_GetAuthorizedPermissions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []string
		if args[2] != nil {
			arg2 = args[2].([]string)
		}
		var arg3 []string
		if args[3] != nil {
			arg3 = args[3].([]string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *RoleServiceInterfaceMock_GetAuthorizedPermissions_Call) Return(strings []string, serviceError *serviceerror.ServiceError) *RoleServiceInterfaceMock_GetAuthorizedPermissions_Call {
	_c.Call.Return(strings, serviceError)
	return _c
}

func (_c *RoleServiceInterfaceMock_GetAuthorizedPermissions_Call) RunAndReturn(run func(ctx context.Context, entityID string, groups []string, requestedPermissions []string) ([]string, *serviceerror.ServiceError)) *RoleServiceInterfaceMock_GetAuthorizedPermissions_Call {
	_c.Call.Return(run)
	return _c
}

// GetRoleAssignments provides a mock function for the type RoleServiceInterfaceMock
func (_mock *RoleServiceInterfaceMock) GetRoleAssignments(ctx context.Context, id string, limit int, offset int, includeDisplay bool) (*role.AssignmentList, *serviceerror.ServiceError) {
	ret := _mock.Called(ctx, id, limit, offset, includeDisplay)

	if len(ret) == 0 {
		panic("no return value specified for GetRoleAssignments")
	}

	var r0 *role.AssignmentList
	var r1 *serviceerror.ServiceError
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int, int, bool) (*role.AssignmentList, *serviceerror.ServiceError)); ok {
		return returnFunc(ctx, id, limit, offset, includeDisplay)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int, int, bool) *role.AssignmentList); ok {
		r0 = returnFunc(ctx, id, limit, offset, includeDisplay)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*role.AssignmentList)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, int, int, bool) *serviceerror.ServiceError); ok {
		r1 = returnFunc(ctx, id, limit, offset, includeDisplay)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*serviceerror.ServiceError)
		}
	}
	return r0, r1
}

// RoleServiceInterfaceMock_GetRoleAssignments_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRoleAssignments'
type RoleServiceInterfaceMock_GetRoleAssignments_Call struct {
	*mock.Call
}

// GetRoleAssignments is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - limit int
//   - offset int
//   - includeDisplay bool
func (_e *RoleServiceInterfaceMock_Expecter) GetRoleAssignments(ctx interface{}, id interface{}, limit interface{}, offset interface{}, includeDisplay interface{}) *RoleServiceInterfaceMock_GetRoleAssignments_Call {
	return &RoleServiceInterfaceMock_GetRoleAssignments_Call{Call: _e.mock.On("GetRoleAssignments", ctx, id, limit, offset, includeDisplay)}
}

func (_c *RoleServiceInterfaceMock_GetRoleAssignments_Call) Run(run func(ctx context.Context, id string, limit int, offset int, includeDisplay bool)) *RoleServiceInterfaceMock_GetRoleAssignments_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		var arg3 int
		if args[3] != nil {
			arg3 = args[3].(int)
		}
		var arg4 bool
		if args[4] != nil {
			arg4 = args[4].(bool)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *RoleServiceInterfaceMock_GetRoleAssignments_Call) Return(assignmentList *role.AssignmentList, serviceError *serviceerror.ServiceError) *RoleServiceInterfaceMock_GetRoleAssignments_Call {
	_c.Call.Return(assignmentList, serviceError)
	return _c
}

func (_c *RoleServiceInterfaceMock_GetRoleAssignments_Call) RunAndReturn(run func(ctx context.Context, id string, limit int, offset int, includeDisplay bool) (*role.AssignmentList, *serviceerror.ServiceError)) *RoleServiceInterfaceMock_GetRoleAssignments_Call {
	_c.Call.Return(run)
	return _c
}

// GetRoleAssignmentsByType provides a mock function for the type RoleServiceInterfaceMock
func (_mock *RoleServiceInterfaceMock) GetRoleAssignmentsByType(ctx context.Context, id string, limit int, offset int, includeDisplay bool, assigneeType string) (*role.AssignmentList, *serviceerror.ServiceError) {
	ret := _mock.Called(ctx, id, limit, offset, includeDisplay, assigneeType)

	if len(ret) == 0 {
		panic("no return value specified for GetRoleAssignmentsByType")
	}

	var r0 *role.AssignmentList
	var r1 *serviceerror.ServiceError
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int, int, bool, string) (*role.AssignmentList, *serviceerror.ServiceError)); ok {
		return returnFunc(ctx, id, limit, offset, includeDisplay, assigneeType)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int, int, bool, string) *role.AssignmentList); ok {
		r0 = returnFunc(ctx, id, limit, offset, includeDisplay, assigneeType)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*role.AssignmentList)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, int, int, bool, string) *serviceerror.ServiceError); ok {
		r1 = returnFunc(ctx, id, limit, offset, includeDisplay, assigneeType)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*serviceerror.ServiceError)
		}
	}
	return r0, r1
}

// RoleServiceInterfaceMock_GetRoleAssignmentsByType_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRoleAssignmentsByType'
type RoleServiceInterfaceMock_GetRoleAssignmentsByType_Call struct {
	*mock.Call
}

// GetRoleAssignmentsByType is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - limit int
//   - offset int
//   - includeDisplay bool
//   - assigneeType string
func (_e *RoleServiceInterfaceMock_Expecter) GetRoleAssignmentsByType(ctx interface{}, id interface{}, limit interface{}, offset interface{}, includeDisplay interface{}, assigneeType interface{}) *RoleServiceInterfaceMock_GetRoleAssignmentsByType_Call {
	return &RoleServiceInterfaceMock_GetRoleAssignmentsByType_Call{Call: _e.mock.On("GetRoleAssignmentsByType", ctx, id, limit, offset, includeDisplay, assigneeType)}
}

func (_c *RoleServiceInterfaceMock_GetRoleAssignmentsByType_Call) Run(run func(ctx context.Context, id string, limit int, offset int, includeDisplay bool, assigneeType string)) *RoleServiceInterfaceMock_GetRoleAssignmentsByType_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		var arg3 int
		if args[3] != nil {
			arg3 = args[3].(int)
		}
		var arg4 bool
		if args[4] != nil {
			arg4 = args[4].(bool)
		}
		var arg5 string
		if args[5] != nil {
			arg5 = args[5].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
		)
	})
	return _c
}

func (_c *RoleServiceInterfaceMock_GetRoleAssignmentsByType_Call) Return(assignmentList *role.AssignmentList, serviceError *serviceerror.ServiceError) *RoleServiceInterfaceMock_GetRoleAssignmentsByType_Call {
	_c.Call.Return(assignmentList, serviceError)
	return _c
}

func (_c *RoleServiceInterfaceMock_GetRoleAssignmentsByType_Call) RunAndReturn(run func(ctx context.Context, id string, limit int, offset int, includeDisplay bool, assigneeType string) (*role.AssignmentList, *serviceerror.ServiceError)) *RoleServiceInterfaceMock_GetRoleAssignmentsByType_Call {
	_c.Call.Return(run)
	return _c
}

// GetRoleList provides a mock function for the type RoleServiceInterfaceMock
func (_mock *RoleServiceInterfaceMock) GetRoleList(ctx context.Context, limit int, offset int) (*role.RoleList, *serviceerror.ServiceError) {
	ret := _mock.Called(ctx, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for GetRoleList")
	}

	var r0 *role.RoleList
	var r1 *serviceerror.ServiceError
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, int) (*role.RoleList, *serviceerror.ServiceError)); ok {
		return returnFunc(ctx, limit, offset)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, int) *role.RoleList); ok {
		r0 = returnFunc(ctx, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*role.RoleList)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int, int) *serviceerror.ServiceError); ok {
		r1 = returnFunc(ctx, limit, offset)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*serviceerror.ServiceError)
		}
	}
	return r0, r1
}

// RoleServiceInterfaceMock_GetRoleList_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRoleList'
type RoleServiceInterfaceMock_GetRoleList_Call struct {
	*mock.Call
}

// GetRoleList is a helper method to define mock.On call
//   - ctx context.Context
//   - limit int
//   - offset int
func (_e *RoleServiceInterfaceMock_Expecter) GetRoleList(ctx interface{}, limit interface{}, offset interface{}) *RoleServiceInterfaceMock_GetRoleList_Call {
	return &RoleServiceInterfaceMock_GetRoleList_Call{Call: _e.mock.On("GetRoleList", ctx, limit, offset)}
}

func (_c *RoleServiceInterfaceMock_GetRoleList_Call) Run(run func(ctx context.Context, limit int, offset int)) *RoleServiceInterfaceMock_GetRoleList_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *RoleServiceInterfaceMock_GetRoleList_Call) Return(roleList *role.RoleList, serviceError *serviceerror.ServiceError) *RoleServiceInterfaceMock_GetRoleList_Call {
	_c.Call.Return(roleList, serviceError)
	return _c
}

func (_c *RoleServiceInterfaceMock_GetRoleList_Call) RunAndReturn(run func(ctx context.Context, limit int, offset int) (*role.RoleList, *serviceerror.ServiceError)) *RoleServiceInterfaceMock_GetRoleList_Call {
	_c.Call.Return(run)
	return _c
}

// GetRoleWithPermissions provides a mock function for the type RoleServiceInterfaceMock
func (_mock *RoleServiceInterfaceMock) GetRoleWithPermissions(ctx context.Context, id string) (*role.RoleWithPermissions, *serviceerror.ServiceError) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetRoleWithPermissions")
	}

	var r0 *role.RoleWithPermissions
	var r1 *serviceerror.ServiceError
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*role.RoleWithPermissions, *serviceerror.ServiceError)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *role.RoleWithPermissions); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*role.RoleWithPermissions)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) *serviceerror.ServiceError); ok {
		r1 = returnFunc(ctx, id)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*serviceerror.ServiceError)
		}
	}
	return r0, r1
}

// RoleServiceInterfaceMock_GetRoleWithPermissions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRoleWithPermissions'
type RoleServiceInterfaceMock_GetRoleWithPermissions_Call struct {
	*mock.Call
}

// GetRoleWithPermissions is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *RoleServiceInterfaceMock_Expecter) GetRoleWithPermissions(ctx interface{}, id interface{}) *RoleServiceInterfaceMock_GetRoleWithPermissions_Call {
	return &RoleServiceInterfaceMock_GetRoleWithPermissions_Call{Call: _e.mock.On("GetRoleWithPermissions", ctx, id)}
}

func (_c *RoleServiceInterfaceMock_GetRoleWithPermissions_Call) Run(run func(ctx context.Context, id string)) *RoleServiceInterfaceMock_GetRoleWithPermissions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *RoleServiceInterfaceMock_GetRoleWithPermissions_Call) Return(roleWithPermissions *role.RoleWithPermissions, serviceError *serviceerror.ServiceError) *RoleServiceInterfaceMock_GetRoleWithPermissions_Call {
	_c.Call.Return(roleWithPermissions, serviceError)
	return _c
}

func (_c *RoleServiceInterfaceMock_GetRoleWithPermissions_Call) RunAndReturn(run func(ctx context.Context, id string) (*role.RoleWithPermissions, *serviceerror.ServiceError)) *RoleServiceInterfaceMock_GetRoleWithPermissions_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserRoles provides a mock function for the type RoleServiceInterfaceMock
func (_mock *RoleServiceInterfaceMock) GetUserRoles(ctx context.Context, entityID string, groupIDs []string) ([]string, *serviceerror.ServiceError) {
	ret := _mock.Called(ctx, entityID, groupIDs)

	if len(ret) == 0 {
		panic("no return value specified for GetUserRoles")
	}

	var r0 []string
	var r1 *serviceerror.ServiceError
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, []string) ([]string, *serviceerror.ServiceError)); ok {
		return returnFunc(ctx, entityID, groupIDs)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, []string) []string); ok {
		r0 = returnFunc(ctx, entityID, groupIDs)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, []string) *serviceerror.ServiceError); ok {
		r1 = returnFunc(ctx, entityID, groupIDs)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*serviceerror.ServiceError)
		}
	}
	return r0, r1
}

// RoleServiceInterfaceMock_GetUserRoles_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserRoles'
type RoleServiceInterfaceMock_GetUserRoles_Call struct {
	*mock.Call
}

// GetUserRoles is a helper method to define mock.On call
//   - ctx context.Context
//   - entityID string
//   - groupIDs []string
func (_e *RoleServiceInterfaceMock_Expecter) GetUserRoles(ctx interface{}, entityID interface{}, groupIDs interface{}) *RoleServiceInterfaceMock_GetUserRoles_Call {
	return &RoleServiceInterfaceMock_GetUserRoles_Call{Call: _e.mock.On("GetUserRoles", ctx, entityID, groupIDs)}
}

func (_c *RoleServiceInterfaceMock_GetUserRoles_Call) Run(run func(ctx context.Context, entityID string, groupIDs []string)) *RoleServiceInterfaceMock_GetUserRoles_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []string
		if args[2] != nil {
			arg2 = args[2].([]string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *RoleServiceInterfaceMock_GetUserRoles_Call) Return(strings []string, serviceError *serviceerror.ServiceError) *RoleServiceInterfaceMock_GetUserRoles_Call {
	_c.Call.Return(strings, serviceError)
	return _c
}

func (_c *RoleServiceInterfaceMock_GetUserRoles_Call) RunAndReturn(run func(ctx context.Context, entityID string, groupIDs []string) ([]string, *serviceerror.ServiceError)) *RoleServiceInterfaceMock_GetUserRoles_Call {
	_c.Call.Return(run)
	return _c
}

// IsRoleDeclarative provides a mock function for the type RoleServiceInterfaceMock
func (_mock *RoleServiceInterfaceMock) IsRoleDeclarative(ctx context.Context, id string) (bool, *serviceerror.ServiceError) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for IsRoleDeclarative")
	}

	var r0 bool
	var r1 *serviceerror.ServiceError
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (bool, *serviceerror.ServiceError)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) *serviceerror.ServiceError); ok {
		r1 = returnFunc(ctx, id)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*serviceerror.ServiceError)
		}
	}
	return r0, r1
}

// RoleServiceInterfaceMock_IsRoleDeclarative_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsRoleDeclarative'
type RoleServiceInterfaceMock_IsRoleDeclarative_Call struct {
	*mock.Call
}

// IsRoleDeclarative is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *RoleServiceInterfaceMock_Expecter) IsRoleDeclarative(ctx interface{}, id interface{}) *RoleServiceInterfaceMock_IsRoleDeclarative_Call {
	return &RoleServiceInterfaceMock_IsRoleDeclarative_Call{Call: _e.mock.On("IsRoleDeclarative", ctx, id)}
}

func (_c *RoleServiceInterfaceMock_IsRoleDeclarative_Call) Run(run func(ctx context.Context, id string)) *RoleServiceInterfaceMock_IsRoleDeclarative_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *RoleServiceInterfaceMock_IsRoleDeclarative_Call) Return(b bool, serviceError *serviceerror.ServiceError) *RoleServiceInterfaceMock_IsRoleDeclarative_Call {
	_c.Call.Return(b, serviceError)
	return _c
}

func (_c *RoleServiceInterfaceMock_IsRoleDeclarative_Call) RunAndReturn(run func(ctx context.Context, id string) (bool, *serviceerror.ServiceError)) *RoleServiceInterfaceMock_IsRoleDeclarative_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveAssignments provides a mock function for the type RoleServiceInterfaceMock
func (_mock *RoleServiceInterfaceMock) RemoveAssignments(ctx context.Context, id string, assignments []role.RoleAssignment) *serviceerror.ServiceError {
	ret := _mock.Called(ctx, id, assignments)

	if len(ret) == 0 {
		panic("no return value specified for RemoveAssignments")
	}

	var r0 *serviceerror.ServiceError
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, []role.RoleAssignment) *serviceerror.ServiceError); ok {
		r0 = returnFunc(ctx, id, assignments)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*serviceerror.ServiceError)
		}
	}
	return r0
}

// RoleServiceInterfaceMock_RemoveAssignments_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveAssignments'
type RoleServiceInterfaceMock_RemoveAssignments_Call struct {
	*mock.Call
}

// RemoveAssignments is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - assignments []role.RoleAssignment
func (_e *RoleServiceInterfaceMock_Expecter) RemoveAssignments(ctx interface{}, id interface{}, assignments interface{}) *RoleServiceInterfaceMock_RemoveAssignments_Call {
	return &RoleServiceInterfaceMock_RemoveAssignments_Call{Call: _e.mock.On("RemoveAssignments", ctx, id, assignments)}
}

func (_c *RoleServiceInterfaceMock_RemoveAssignments_Call) Run(run func(ctx context.Context, id string, assignments []role.RoleAssignment)) *RoleServiceInterfaceMock_RemoveAssignments_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []role.RoleAssignment
		if args[2] != nil {
			arg2 = args[2].([]role.RoleAssignment)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *RoleServiceInterfaceMock_RemoveAssignments_Call) Return(serviceError *serviceerror.ServiceError) *RoleServiceInterfaceMock_RemoveAssignments_Call {
	_c.Call.Return(serviceError)
	return _c
}

func (_c *RoleServiceInterfaceMock_RemoveAssignments_Call) RunAndReturn(run func(ctx context.Context, id string, assignments []role.RoleAssignment) *serviceerror.ServiceError) *RoleServiceInterfaceMock_RemoveAssignments_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateRoleWithPermissions provides a mock function for the type RoleServiceInterfaceMock
func (_mock *RoleServiceInterfaceMock) UpdateRoleWithPermissions(ctx context.Context, id string, role1 role.RoleUpdateDetail) (*role.RoleWithPermissions, *serviceerror.ServiceError) {
	ret := _mock.Called(ctx, id, role1)

	if len(ret) == 0 {
		panic("no return value specified for UpdateRoleWithPermissions")
	}

	var r0 *role.RoleWithPermissions
	var r1 *serviceerror.ServiceError
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, role.RoleUpdateDetail) (*role.RoleWithPermissions, *serviceerror.ServiceError)); ok {
		return returnFunc(ctx, id, role1)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, role.RoleUpdateDetail) *role.RoleWithPermissions); ok {
		r0 = returnFunc(ctx, id, role1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*role.RoleWithPermissions)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, role.RoleUpdateDetail) *serviceerror.ServiceError); ok {
		r1 = returnFunc(ctx, id, role1)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*serviceerror.ServiceError)
		}
	}
	return r0, r1
}

// RoleServiceInterfaceMock_UpdateRoleWithPermissions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateRoleWithPermissions'
type RoleServiceInterfaceMock_UpdateRoleWithPermissions_Call struct {
	*mock.Call
}

// UpdateRoleWithPermissions is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - role1 role.RoleUpdateDetail
func (_e *RoleServiceInterfaceMock_Expecter) UpdateRoleWithPermissions(ctx interface{}, id interface{}, role1 interface{}) *RoleServiceInterfaceMock_UpdateRoleWithPermissions_Call {
	return &RoleServiceInterfaceMock_UpdateRoleWithPermissions_Call{Call: _e.mock.On("UpdateRoleWithPermissions", ctx, id, role1)}
}

func (_c *RoleServiceInterfaceMock_UpdateRoleWithPermissions_Call) Run(run func(ctx context.Context, id string, role1 role.RoleUpdateDetail)) *RoleServiceInterfaceMock_UpdateRoleWithPermissions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 role.RoleUpdateDetail
		if args[2] != nil {
			arg2 = args[2].(role.RoleUpdateDetail)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *RoleServiceInterfaceMock_UpdateRoleWithPermissions_Call) Return(roleWithPermissions *role.RoleWithPermissions, serviceError *serviceerror.ServiceError) *RoleServiceInterfaceMock_UpdateRoleWithPermissions_Call {
	_c.Call.Return(roleWithPermissions, serviceError)
	return _c
}

func (_c *RoleServiceInterfaceMock_UpdateRoleWithPermissions_Call) RunAndReturn(run func(ctx context.Context, id string, role1 role.RoleUpdateDetail) (*role.RoleWithPermissions, *serviceerror.ServiceError)) *RoleServiceInterfaceMock_UpdateRoleWithPermissions_Call {
	_c.Call.Return(run)
	return _c
}
