// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package flowexecmock

import (
	"context"

	"github.com/senthalan/thunder/backend/internal/flow/flowexec"
	mock "github.com/stretchr/testify/mock"
)

// newFlowStoreInterfaceMock creates a new instance of flowStoreInterfaceMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newFlowStoreInterfaceMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *flowStoreInterfaceMock {
	mock := &flowStoreInterfaceMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// flowStoreInterfaceMock is an autogenerated mock type for the flowStoreInterface type
type flowStoreInterfaceMock struct {
	mock.Mock
}

type flowStoreInterfaceMock_Expecter struct {
	mock *mock.Mock
}

func (_m *flowStoreInterfaceMock) EXPECT() *flowStoreInterfaceMock_Expecter {
	return &flowStoreInterfaceMock_Expecter{mock: &_m.Mock}
}

// DeleteFlowContext provides a mock function for the type flowStoreInterfaceMock
func (_mock *flowStoreInterfaceMock) DeleteFlowContext(ctx context.Context, executionID string) error {
	ret := _mock.Called(ctx, executionID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteFlowContext")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, executionID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// flowStoreInterfaceMock_DeleteFlowContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteFlowContext'
type flowStoreInterfaceMock_DeleteFlowContext_Call struct {
	*mock.Call
}

// DeleteFlowContext is a helper method to define mock.On call
//   - ctx context.Context
//   - executionID string
func (_e *flowStoreInterfaceMock_Expecter) DeleteFlowContext(ctx interface{}, executionID interface{}) *flowStoreInterfaceMock_DeleteFlowContext_Call {
	return &flowStoreInterfaceMock_DeleteFlowContext_Call{Call: _e.mock.On("DeleteFlowContext", ctx, executionID)}
}

func (_c *flowStoreInterfaceMock_DeleteFlowContext_Call) Run(run func(ctx context.Context, executionID string)) *flowStoreInterfaceMock_DeleteFlowContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *flowStoreInterfaceMock_DeleteFlowContext_Call) Return(err error) *flowStoreInterfaceMock_DeleteFlowContext_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *flowStoreInterfaceMock_DeleteFlowContext_Call) RunAndReturn(run func(ctx context.Context, executionID string) error) *flowStoreInterfaceMock_DeleteFlowContext_Call {
	_c.Call.Return(run)
	return _c
}

// GetFlowContext provides a mock function for the type flowStoreInterfaceMock
func (_mock *flowStoreInterfaceMock) GetFlowContext(ctx context.Context, executionID string) (*flowexec.FlowContextDB, error) {
	ret := _mock.Called(ctx, executionID)

	if len(ret) == 0 {
		panic("no return value specified for GetFlowContext")
	}

	var r0 *flowexec.FlowContextDB
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*flowexec.FlowContextDB, error)); ok {
		return returnFunc(ctx, executionID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *flowexec.FlowContextDB); ok {
		r0 = returnFunc(ctx, executionID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*flowexec.FlowContextDB)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, executionID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// flowStoreInterfaceMock_GetFlowContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetFlowContext'
type flowStoreInterfaceMock_GetFlowContext_Call struct {
	*mock.Call
}

// GetFlowContext is a helper method to define mock.On call
//   - ctx context.Context
//   - executionID string
func (_e *flowStoreInterfaceMock_Expecter) GetFlowContext(ctx interface{}, executionID interface{}) *flowStoreInterfaceMock_GetFlowContext_Call {
	return &flowStoreInterfaceMock_GetFlowContext_Call{Call: _e.mock.On("GetFlowContext", ctx, executionID)}
}

func (_c *flowStoreInterfaceMock_GetFlowContext_Call) Run(run func(ctx context.Context, executionID string)) *flowStoreInterfaceMock_GetFlowContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *flowStoreInterfaceMock_GetFlowContext_Call) Return(flowContextDB *flowexec.FlowContextDB, err error) *flowStoreInterfaceMock_GetFlowContext_Call {
	_c.Call.Return(flowContextDB, err)
	return _c
}

func (_c *flowStoreInterfaceMock_GetFlowContext_Call) RunAndReturn(run func(ctx context.Context, executionID string) (*flowexec.FlowContextDB, error)) *flowStoreInterfaceMock_GetFlowContext_Call {
	_c.Call.Return(run)
	return _c
}

// StoreFlowContext provides a mock function for the type flowStoreInterfaceMock
func (_mock *flowStoreInterfaceMock) StoreFlowContext(ctx context.Context, engineCtx flowexec.EngineContext, expirySeconds int64) error {
	ret := _mock.Called(ctx, engineCtx, expirySeconds)

	if len(ret) == 0 {
		panic("no return value specified for StoreFlowContext")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, flowexec.EngineContext, int64) error); ok {
		r0 = returnFunc(ctx, engineCtx, expirySeconds)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// flowStoreInterfaceMock_StoreFlowContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StoreFlowContext'
type flowStoreInterfaceMock_StoreFlowContext_Call struct {
	*mock.Call
}

// StoreFlowContext is a helper method to define mock.On call
//   - ctx context.Context
//   - engineCtx flowexec.EngineContext
//   - expirySeconds int64
func (_e *flowStoreInterfaceMock_Expecter) StoreFlowContext(ctx interface{}, engineCtx interface{}, expirySeconds interface{}) *flowStoreInterfaceMock_StoreFlowContext_Call {
	return &flowStoreInterfaceMock_StoreFlowContext_Call{Call: _e.mock.On("StoreFlowContext", ctx, engineCtx, expirySeconds)}
}

func (_c *flowStoreInterfaceMock_StoreFlowContext_Call) Run(run func(ctx context.Context, engineCtx flowexec.EngineContext, expirySeconds int64)) *flowStoreInterfaceMock_StoreFlowContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 flowexec.EngineContext
		if args[1] != nil {
			arg1 = args[1].(flowexec.EngineContext)
		}
		var arg2 int64
		if args[2] != nil {
			arg2 = args[2].(int64)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *flowStoreInterfaceMock_StoreFlowContext_Call) Return(err error) *flowStoreInterfaceMock_StoreFlowContext_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *flowStoreInterfaceMock_StoreFlowContext_Call) RunAndReturn(run func(ctx context.Context, engineCtx flowexec.EngineContext, expirySeconds int64) error) *flowStoreInterfaceMock_StoreFlowContext_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateFlowContext provides a mock function for the type flowStoreInterfaceMock
func (_mock *flowStoreInterfaceMock) UpdateFlowContext(ctx context.Context, engineCtx flowexec.EngineContext) error {
	ret := _mock.Called(ctx, engineCtx)

	if len(ret) == 0 {
		panic("no return value specified for UpdateFlowContext")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, flowexec.EngineContext) error); ok {
		r0 = returnFunc(ctx, engineCtx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// flowStoreInterfaceMock_UpdateFlowContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateFlowContext'
type flowStoreInterfaceMock_UpdateFlowContext_Call struct {
	*mock.Call
}

// UpdateFlowContext is a helper method to define mock.On call
//   - ctx context.Context
//   - engineCtx flowexec.EngineContext
func (_e *flowStoreInterfaceMock_Expecter) UpdateFlowContext(ctx interface{}, engineCtx interface{}) *flowStoreInterfaceMock_UpdateFlowContext_Call {
	return &flowStoreInterfaceMock_UpdateFlowContext_Call{Call: _e.mock.On("UpdateFlowContext", ctx, engineCtx)}
}

func (_c *flowStoreInterfaceMock_UpdateFlowContext_Call) Run(run func(ctx context.Context, engineCtx flowexec.EngineContext)) *flowStoreInterfaceMock_UpdateFlowContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 flowexec.EngineContext
		if args[1] != nil {
			arg1 = args[1].(flowexec.EngineContext)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *flowStoreInterfaceMock_UpdateFlowContext_Call) Return(err error) *flowStoreInterfaceMock_UpdateFlowContext_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *flowStoreInterfaceMock_UpdateFlowContext_Call) RunAndReturn(run func(ctx context.Context, engineCtx flowexec.EngineContext) error) *flowStoreInterfaceMock_UpdateFlowContext_Call {
	_c.Call.Return(run)
	return _c
}
