// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package consentenforcermock

import (
	"context"

	"github.com/senthalan/thunder/backend/internal/authn/consent"
	"github.com/senthalan/thunder/backend/internal/authnprovider/common"
	consent0 "github.com/senthalan/thunder/backend/internal/consent"
	"github.com/senthalan/thunder/backend/internal/system/error/serviceerror"
	mock "github.com/stretchr/testify/mock"
)

// NewConsentEnforcerServiceInterfaceMock creates a new instance of ConsentEnforcerServiceInterfaceMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewConsentEnforcerServiceInterfaceMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *ConsentEnforcerServiceInterfaceMock {
	mock := &ConsentEnforcerServiceInterfaceMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// ConsentEnforcerServiceInterfaceMock is an autogenerated mock type for the ConsentEnforcerServiceInterface type
type ConsentEnforcerServiceInterfaceMock struct {
	mock.Mock
}

type ConsentEnforcerServiceInterfaceMock_Expecter struct {
	mock *mock.Mock
}

func (_m *ConsentEnforcerServiceInterfaceMock) EXPECT() *ConsentEnforcerServiceInterfaceMock_Expecter {
	return &ConsentEnforcerServiceInterfaceMock_Expecter{mock: &_m.Mock}
}

// RecordConsent provides a mock function for the type ConsentEnforcerServiceInterfaceMock
func (_mock *ConsentEnforcerServiceInterfaceMock) RecordConsent(ctx context.Context, ouID string, appID string, userID string, decisions *consent.ConsentDecisions, sessionToken string, validityPeriod int64) (*consent0.Consent, *serviceerror.ServiceError) {
	ret := _mock.Called(ctx, ouID, appID, userID, decisions, sessionToken, validityPeriod)

	if len(ret) == 0 {
		panic("no return value specified for RecordConsent")
	}

	var r0 *consent0.Consent
	var r1 *serviceerror.ServiceError
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string, *consent.ConsentDecisions, string, int64) (*consent0.Consent, *serviceerror.ServiceError)); ok {
		return returnFunc(ctx, ouID, appID, userID, decisions, sessionToken, validityPeriod)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string, *consent.ConsentDecisions, string, int64) *consent0.Consent); ok {
		r0 = returnFunc(ctx, ouID, appID, userID, decisions, sessionToken, validityPeriod)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*consent0.Consent)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, string, *consent.ConsentDecisions, string, int64) *serviceerror.ServiceError); ok {
		r1 = returnFunc(ctx, ouID, appID, userID, decisions, sessionToken, validityPeriod)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*serviceerror.ServiceError)
		}
	}
	return r0, r1
}

// ConsentEnforcerServiceInterfaceMock_RecordConsent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RecordConsent'
type ConsentEnforcerServiceInterfaceMock_RecordConsent_Call struct {
	*mock.Call
}

// RecordConsent is a helper method to define mock.On call
//   - ctx context.Context
//   - ouID string
//   - appID string
//   - userID string
//   - decisions *consent.ConsentDecisions
//   - sessionToken string
//   - validityPeriod int64
func (_e *ConsentEnforcerServiceInterfaceMock_Expecter) RecordConsent(ctx interface{}, ouID interface{}, appID interface{}, userID interface{}, decisions interface{}, sessionToken interface{}, validityPeriod interface{}) *ConsentEnforcerServiceInterfaceMock_RecordConsent_Call {
	return &ConsentEnforcerServiceInterfaceMock_RecordConsent_Call{Call: _e.mock.On("RecordConsent", ctx, ouID, appID, userID, decisions, sessionToken, validityPeriod)}
}

func (_c *ConsentEnforcerServiceInterfaceMock_RecordConsent_Call) Run(run func(ctx context.Context, ouID string, appID string, userID string, decisions *consent.ConsentDecisions, sessionToken string, validityPeriod int64)) *ConsentEnforcerServiceInterfaceMock_RecordConsent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 *consent.ConsentDecisions
		if args[4] != nil {
			arg4 = args[4].(*consent.ConsentDecisions)
		}
		var arg5 string
		if args[5] != nil {
			arg5 = args[5].(string)
		}
		var arg6 int64
		if args[6] != nil {
			arg6 = args[6].(int64)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
			arg6,
		)
	})
	return _c
}

func (_c *ConsentEnforcerServiceInterfaceMock_RecordConsent_Call) Return(consent1 *consent0.Consent, serviceError *serviceerror.ServiceError) *ConsentEnforcerServiceInterfaceMock_RecordConsent_Call {
	_c.Call.Return(consent1, serviceError)
	return _c
}

func (_c *ConsentEnforcerServiceInterfaceMock_RecordConsent_Call) RunAndReturn(run func(ctx context.Context, ouID string, appID string, userID string, decisions *consent.ConsentDecisions, sessionToken string, validityPeriod int64) (*consent0.Consent, *serviceerror.ServiceError)) *ConsentEnforcerServiceInterfaceMock_RecordConsent_Call {
	_c.Call.Return(run)
	return _c
}

// ResolveConsent provides a mock function for the type ConsentEnforcerServiceInterfaceMock
func (_mock *ConsentEnforcerServiceInterfaceMock) ResolveConsent(ctx context.Context, ouID string, appID string, userID string, essentialAttributes []string, optionalAttributes []string, availableAttributes *common.AttributesResponse) (*consent.ConsentPromptData, *serviceerror.ServiceError) {
	ret := _mock.Called(ctx, ouID, appID, userID, essentialAttributes, optionalAttributes, availableAttributes)

	if len(ret) == 0 {
		panic("no return value specified for ResolveConsent")
	}

	var r0 *consent.ConsentPromptData
	var r1 *serviceerror.ServiceError
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string, []string, []string, *common.AttributesResponse) (*consent.ConsentPromptData, *serviceerror.ServiceError)); ok {
		return returnFunc(ctx, ouID, appID, userID, essentialAttributes, optionalAttributes, availableAttributes)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string, []string, []string, *common.AttributesResponse) *consent.ConsentPromptData); ok {
		r0 = returnFunc(ctx, ouID, appID, userID, essentialAttributes, optionalAttributes, availableAttributes)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*consent.ConsentPromptData)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, string, []string, []string, *common.AttributesResponse) *serviceerror.ServiceError); ok {
		r1 = returnFunc(ctx, ouID, appID, userID, essentialAttributes, optionalAttributes, availableAttributes)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*serviceerror.ServiceError)
		}
	}
	return r0, r1
}

// ConsentEnforcerServiceInterfaceMock_ResolveConsent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ResolveConsent'
type ConsentEnforcerServiceInterfaceMock_ResolveConsent_Call struct {
	*mock.Call
}

// ResolveConsent is a helper method to define mock.On call
//   - ctx context.Context
//   - ouID string
//   - appID string
//   - userID string
//   - essentialAttributes []string
//   - optionalAttributes []string
//   - availableAttributes *common.AttributesResponse
func (_e *ConsentEnforcerServiceInterfaceMock_Expecter) ResolveConsent(ctx interface{}, ouID interface{}, appID interface{}, userID interface{}, essentialAttributes interface{}, optionalAttributes interface{}, availableAttributes interface{}) *ConsentEnforcerServiceInterfaceMock_ResolveConsent_Call {
	return &ConsentEnforcerServiceInterfaceMock_ResolveConsent_Call{Call: _e.mock.On("ResolveConsent", ctx, ouID, appID, userID, essentialAttributes, optionalAttributes, availableAttributes)}
}

func (_c *ConsentEnforcerServiceInterfaceMock_ResolveConsent_Call) Run(run func(ctx context.Context, ouID string, appID string, userID string, essentialAttributes []string, optionalAttributes []string, availableAttributes *common.AttributesResponse)) *ConsentEnforcerServiceInterfaceMock_ResolveConsent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 []string
		if args[4] != nil {
			arg4 = args[4].([]string)
		}
		var arg5 []string
		if args[5] != nil {
			arg5 = args[5].([]string)
		}
		var arg6 *common.AttributesResponse
		if args[6] != nil {
			arg6 = args[6].(*common.AttributesResponse)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
			arg6,
		)
	})
	return _c
}

func (_c *ConsentEnforcerServiceInterfaceMock_ResolveConsent_Call) Return(consentPromptData *consent.ConsentPromptData, serviceError *serviceerror.ServiceError) *ConsentEnforcerServiceInterfaceMock_ResolveConsent_Call {
	_c.Call.Return(consentPromptData, serviceError)
	return _c
}

func (_c *ConsentEnforcerServiceInterfaceMock_ResolveConsent_Call) RunAndReturn(run func(ctx context.Context, ouID string, appID string, userID string, essentialAttributes []string, optionalAttributes []string, availableAttributes *common.AttributesResponse) (*consent.ConsentPromptData, *serviceerror.ServiceError)) *ConsentEnforcerServiceInterfaceMock_ResolveConsent_Call {
	_c.Call.Return(run)
	return _c
}
